name: 🐞 过期软件包 / out-of-date packages
title: "[out-of-date]: "
labels: [out-of-date]
body:
  - type: markdown
    attributes:
      value: |
        ### 问题类型 / Type of issues

        * 过期软件包 / out-of-date packages

        ----

  - type: textarea
    attributes:
      label: 受影响的软件包 / Affected packages
      value: |
        * （请在此填写包名，每行一个，开头加上星号 / package names, one per line）
    validations:
      required: true
